### ISSUE TITLE
rule ruleSolution failed predicate: {getUnorderedGroupHelper().canLeave(grammarAccess.getSolutionAccess().getUnorderedGroup_3())}?

### ISSUE THREAD

**Issue by Hofschn8** [modal-dsl/modal#16]
Hello, when i try to create a .mdal file (yours demo file is working) - i get following Error : 

rule ruleSolution failed predicate: {getUnorderedGroupHelper().canLeave(grammarAccess.getSolutionAccess().getUnorderedGroup_3())}?

![image](https://user-images.githubusercontent.com/39769648/94273155-5066e100-ff44-11ea-9d98-86f9d7918798.png)

Hopefully you can help 
BR

**Comment by joneug** [comment]
At the moment it is mandatory to define all table types inside a solution (except for `supplemental`). So in addition to the `master` definition, you would have to specify a `document` and the `ledgerEntry` as it is done in the demo. I understand that you might not need the other two. I am working on making these other two optional so that your example will work. This improvement is planned for the next release.

This problem is already tracked in #14. So I am closing this issue.

**Comment by joneug** [comment]
This issue was fixed in version 0.4.0 of the `mdAL` VS Code Extension. Please update your installation and the example you provided should work.
